services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: unless-stopped
    # command:
    # - /bin/sh
    # - -c
    # # - Double dollars, so that the variable is not expanded by Docker Compose
    # # - Surround by quotes, so that the shell does not split the password
    # # - The ${variable:?message} syntax causes shell to exit with a non-zero
    # #   code and print a message, when the variable is not set or empty
    # - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD variable is not set}" --loadmodule /opt/redis-stack/lib/rejson.so

    ports:
      - '6379:6379'
    volumes: 
      - ./data/redis:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
    env_file:
    - .env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgre:/var/lib/postgresql/data
    env_file: 
    - .env

